#!/bin/bash

# Configuration

# Berlin 2010
# GRIBFILES=../DATA/GRIB/ERA5_20100618_20100704_-5.0_30.0E_40.0_65.0N/ERA5_20100618_20100704_-5.0_30.0E_40.0_65.0N_
# GRIBFILES=../../DATA/GRIB/ERA5_20100618_20100704_-5.0_35.0E_40.0_65.0N/ERA5_20100618_20100704_-5.0_35.0E_40.0_65.0N_
GRIBFILES=../../DATA/GRIB/ERA5_20100610_20100703_-25.0_50.0E_30.0_75.0N/ERA5_20100610_20100703_-25.0_50.0E_30.0_75.0N_

# Basel 2002
# GRIBFILES=../../DATA/GRIB/ERA5_20020609_20020623_-2.0_17.0E_40.0_55.0N/ERA5_20020609_20020623_-2.0_17.0E_40.0_55.0N_

# Berlin 2020
# GRIBFILES=../../DATA/GRIB/ERA5_20200910_20200924_-17_44E_32_73N/ERA5_20200910_20200924_-17_44E_32_73N_

# Shanghai
# GRIBFILES=../../DATA/GRIB/ERA5_20200811_20200820_115.0_130.0E_25.0_40.0N/ERA5_20200811_20200820_115.0_130.0E_25.0_40.0N_
# GRIBFILES=../../DATA/GRIB/ERA5_20200806_20200817_115.0_130.0E_25.0_40.0N/ERA5_20200806_20200817_115.0_130.0E_25.0_40.0N_

VTABLE=ungrib/Variable_Tables/Vtable.ERA-interim.pl
NML_WPS=namelist.wps.pytools
NML_WPS_LAKE=namelist.wps.pytools.lake
NML_WPS_MET=namelist.wps.pytools.met

# Source libraries
echo  source ./load_libraries
source ./load_libraries

# Link namelist
echo ln -sf $NML_WPS namelist.wps
ln -sf $NML_WPS namelist.wps

# Run geogrid
read -p "Run geogrid.exe (y/Enter)? " answer
case ${answer:0:1} in
    y|Y|"" )
        echo Yes
	echo ./geogrid.exe |& tee log.geogrid
	./geogrid.exe |& tee log.geogrid
    ;;
    * )
        echo No
    ;;
esac

# Link Grib files into WPS directory
echo Listing grib files:
ls $GRIBFILES*
read -p "Link grib files into WPS directory (y/Enter)? " answer
case ${answer:0:1} in
    y|Y|"" )
        echo Yes
	echo ./link_grib.csh $GRIBFILES
	./link_grib.csh $GRIBFILES
    ;;
    * )
        echo No
    ;;
esac

# ERA: Link Vtable into WPS directory
echo Listing Vtable for ERA:
ls $VTABLE
read -p "Link Vtable for ERA into WPS directory (y/Enter)? " answer
case ${answer:0:1} in
    y|Y|"" )
        echo Yes
	echo ln -sf $VTABLE Vtable
	ln -sf $VTABLE Vtable
    ;;
    * )
        echo No
    ;;
esac

# ERA: Run ungrib
read -p "Run ungrib.exe for ERA (y/Enter)? " answer
case ${answer:0:1} in
    y|Y|"" )
        echo Yes
	echo ./ungrib.exe |& tee log.ungrib
	./ungrib.exe |& tee log.ungrib
    ;;
    * )
        echo No
    ;;
esac

# Link lake namelist for calculating TAVGSFC
echo ln -sf $NML_WPS_LAKE namelist.wps
ln -sf $NML_WPS_LAKE namelist.wps

# Calculate daily mean surface temperature to substitude SST field only over lakes
read -p "Run avg_tsfc.exe (y/Enter)? " answer
case ${answer:0:1} in
    y|Y|"" )
        echo Yes
	echo ./util/avg_tsfc.exe |& tee log.ungrib
	./util/avg_tsfc.exe |& tee log.ungrib
    ;;
    * )
        echo No
    ;;
esac

# Link namelist for metgrid
echo ln -sf $NML_WPS_MET namelist.wps
ln -sf $NML_WPS_MET namelist.wps

# Run metgrid
read -p "Run metgrid.exe (y/Enter)? " answer
case ${answer:0:1} in
    y|Y|"" )
        echo Yes
	echo ./metgrid.exe |& tee log.metgrid
	./metgrid.exe |& tee log.metgrid
    ;;
    * )
        echo No
    ;;
esac

