#!/bin/bash

# Run without hangup
# (yes | nohup ./runall_wps_era GRIBFILES) &

# Input of gribfiles prefix
GRIBFILES=${1?Error: Input variable GRIBFILES not given. Please specify path e.g. /data/Datasets/GRIB/reanalysis-era5_20221020_20221120_5.0_25.0E_45.0_60.0N/reanalysis-era5_20221020_20221120_5.0_25.0E_45.0_60.0N_}

# Constants
VTABLE=ungrib/Variable_Tables/Vtable.ERA-interim.pl
NML_WPS=namelist.wps.pytools
NML_WPS_LAKE=namelist.wps.pytools.lake
NML_WPS_MET=namelist.wps.pytools.met

# Source libraries
echo  source ./load_libraries
source ./load_libraries

# Link namelist
echo ln -sf $NML_WPS namelist.wps
ln -sf $NML_WPS namelist.wps

# Run geogrid
read -p "Run geogrid.exe (y/Enter)? " answer
case ${answer:0:1} in
    y|Y|"" )
        echo Yes
	echo ./geogrid.exe |& tee log.geogrid
	./geogrid.exe |& tee log.geogrid
    ;;
    * )
        echo No
    ;;
esac

# Link Grib files into WPS directory
echo Listing grib files:
ls $GRIBFILES*
read -p "Link grib files into WPS directory (y/Enter)? " answer
case ${answer:0:1} in
    y|Y|"" )
        echo Yes
	echo ./link_grib.csh $GRIBFILES
	./link_grib.csh $GRIBFILES
    ;;
    * )
        echo No
    ;;
esac

# ERA: Link Vtable into WPS directory
echo Listing Vtable for ERA:
ls $VTABLE
read -p "Link Vtable for ERA into WPS directory (y/Enter)? " answer
case ${answer:0:1} in
    y|Y|"" )
        echo Yes
	echo ln -sf $VTABLE Vtable
	ln -sf $VTABLE Vtable
    ;;
    * )
        echo No
    ;;
esac

# ERA: Run ungrib
read -p "Run ungrib.exe for ERA (y/Enter)? " answer
case ${answer:0:1} in
    y|Y|"" )
        echo Yes
	echo ./ungrib.exe |& tee log.ungrib
	./ungrib.exe |& tee log.ungrib
    ;;
    * )
        echo No
    ;;
esac

# Link lake namelist for calculating TAVGSFC
echo ln -sf $NML_WPS_LAKE namelist.wps
ln -sf $NML_WPS_LAKE namelist.wps

# Calculate daily mean surface temperature to substitude SST field only over lakes
read -p "Run avg_tsfc.exe (y/Enter)? " answer
case ${answer:0:1} in
    y|Y|"" )
        echo Yes
	echo ./util/avg_tsfc.exe |& tee log.avgtsfc
	./util/avg_tsfc.exe |& tee log.avgtsfc
    ;;
    * )
        echo No
    ;;
esac

# Link namelist for metgrid
echo ln -sf $NML_WPS_MET namelist.wps
ln -sf $NML_WPS_MET namelist.wps

# Run metgrid
read -p "Run metgrid.exe (y/Enter)? " answer
case ${answer:0:1} in
    y|Y|"" )
        echo Yes
	echo ./metgrid.exe |& tee log.metgrid
	./metgrid.exe |& tee log.metgrid
    ;;
    * )
        echo No
    ;;
esac

